linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - lll
    - misspell
    - nakedret
    - exportloopref
    - unconvert
    - whitespace
    - wsl
linters-settings:
  funlen:
    lines: 100
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen